export enum CampaignEvents {
    // Campaign Draft  Tasks
    CAMPAIGN_DRAFT_SUCCESS = "CAMPAIGN_DRAFT_SUCCESS",
    

    // Campaign Publish tasks
    CAMPAIGN_PUBLISH_CONTENT = "CAMPAIGN_PUBLISH_CONTENT",
    CAMPAIGN_PUBLISH_DO_SM_TRANSACTION = "CAMPAIGN_DO_SM_TRANSACTION",
    CAMPAIGN_PUBLISH_SECOND_CONTENT = "CAMPAIGN_PUBLISH_SECOND_CONTENT",

    // Error Handling
    CAMPAIGN_PUBLISH_ERROR = "CAMPAIGN_PUBLISH_ERROR",
    CAMPAIGN_DRAFT_ERROR = "CAMPAIGN_DRAFT_ERROR",
} 

export enum CampaignSheduledEvents {
    CAMPAIGN_CLOSE_OPERATION = "CAMPAIGN_CLOSE_OPERATION",
}