export enum CampaignEvents {
  // Campaign Draft Tasks
  CAMPAIGN_DRAFT_SUCCESS = 'CAMPAIGN_DRAFT_SUCCESS',
  CAMPAIGN_DRAFT_ERROR = 'CAMPAIGN_DRAFT_ERROR',

  // Campaign Publish tasks
  CAMPAIGN_PUBLISH_CONTENT = 'CAMPAIGN_PUBLISH_CONTENT',
  CAMPAIGN_PUBLISH_DO_SM_TRANSACTION = 'CAMPAIGN_DO_SM_TRANSACTION',
  CAMPAIGN_PUBLISH_SECOND_CONTENT = 'CAMPAIGN_PUBLISH_SECOND_CONTENT',
  CAMPAIGN_PUBLISH_ERROR = 'CAMPAIGN_PUBLISH_ERROR',

  // Campaign Closing and Reward Recalculation (Equal Distribution)
  CAMPAIGN_CLOSING_SM_TRANSACTION = 'CAMPAIGN_CLOSING_SM_TRANSACTION',
  CAMPAIGN_CLOSING_COLLECT_ENGAGEMENT_LIKE_AND_RETWEET = 'CAMPAIGN_CLOSING_COLLECT_ENGAGEMENT_LIKE_AND_RETWEET',
  CAMPAIGN_CLOSING_RECALCULATE_REWARDS_RATES = 'CAMPAIGN_CLOSING_RECALCULATE_REWARDS_RATES',
  CAMPAIGN_CLOSING_DISTRIBUTE_AUTO_REWARDS = 'CAMPAIGN_CLOSING_DISTRIBUTE_AUTO_REWARDS',
  CAMPAIGN_CLOSING_ERROR = 'CAMPAIGN_CLOSING_ERROR',

  // Campaign Expiration tasks
  CAMPAIGN_EXPIRATION_CAL_TOTAL_AMOUNT_REWARDED = 'CAMPAIGN_EXPIRATION_CAL_TOTAL_AMOUNT_REWARDED',
  CAMPAIGN_EXPIRATION_MARK_SM_AS_EXPIRED = 'CAMPAIGN_EXPIRATION_MARK_SM_AS_EXPIRED',
  CAMPAIGN_EXPIRATION_REFUND_REMAINING_BUDGET = 'CAMPAIGN_EXPIRATION_REFUND_REMAINING_BUDGET',
  CAMPAIGN_EXPIRATION_ERROR = 'CAMPAIGN_EXPIRATION_ERROR',
}

export enum CampaignScheduledEvents {
  CAMPAIGN_CLOSE_OPERATION = 'CAMPAIGN_CLOSE_OPERATION',
  CAMPAIGN_EXPIRATION_OPERATION = 'CAMPAIGN_EXPIRATION_OPERATION',
  V201_ENGAGEMENT_DATA_COLLECTION = 'V201_ENGAGEMENT_DATA_COLLECTION',
  CAMPAIGN_CLOSING_COLLECT_ENGAGEMENT_DATA_QUOTE_AND_REPLY = 'CAMPAIGN_CLOSING_COLLECT_ENGAGEMENT_DATA_QUOTE_AND_REPLY',
}
