export enum TransactionEvents {
    // Transaction events Related to Campaign lifecycle
    TRANSACTION_CL_PUBLISH = "TRANSACTION_CAMPAGN_LIFECYCLE_PUBLISH",
    TRANSACTION_CL_UNPUBLISH = "TRANSACTION_CAMPAGN_LIFECYCLE_UNPUBLISH",
    TRANSACTION_CL_CLOSE = "TRANSACTION_CAMPAGN_LIFECYCLE_CLOSE",
    TRANSACTION_CL_ARCHIVE = "TRANSACTION_CAMPAGN_LIFECYCLE_ARCHIVE",
    TRANSACTION_CL_REJECT = "TRANSACTION_CAMPAGN_LIFECYCLE_REJECT",
    TRANSACTION_CL_APPROVE = "TRANSACTION_CAMPAGN_LIFECYCLE_APPROVE",

    // Transaction events Related to intractor rewarding;
    TRANSACTION_IR_PAY = "TRANSACTION_REWARD",
    TRANSACTION_IR_FAILED = "TRANSACTION_REWARD_FAILED",

    // Transaction Topup events
    TRANSACTION_TOPUP_INIATE = "TRANSACTION_TOPUP_INIATE",
    TRANSACTION_TOPUP_VERIFIED = "TRANSACTION_TOPUP_VERIFIED",
    TRANSACTION_TOPUP_FAILED = "TRANSACTION_TOPUP_FAILED",
    TRANSACTION_TOPUP_SUCCESS = "TRANSACTION_TOPUP_SUCCESS",

    // Transaction Withdraw events
    TRANSACTION_WITHDRAW_INIATE = "TRANSACTION_WITHDRAW_INIATE",
    TRANSACTION_WITHDRAW_VERIFIED = "TRANSACTION_WITHDRAW_VERIFIED",
    TRANSACTION_WITHDRAW_FAILED = "TRANSACTION_WITHDRAW_FAILED",
    TRANSACTION_WITHDRAW_SUCCESS = "TRANSACTION_WITHDRAW_SUCCESS",
}
