name: Connect to DigitalOcean Droplet

on:
  push:
    branches:
      - staging

jobs:
  ssh-to-droplet:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Connect to DigitalOcean Droplet via SSH
      env:
        SSH_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        SSH_PASSWORD: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        SSH_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" << EOF
          echo "Running 'ls -al /root/hashbuzz-dev/dApp-backend' command..."
          ls -al /root/hashbuzz-dev/dApp-backend
          echo "Exporting PATH for Node.js..."
          export PATH=$PATH:/usr/local/bin
          echo "Running 'npm --version' command..."
          npm --version
          echo "Running 'node --version' command..."
          node --version
        EOF

