name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Access to DigitalOcean
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            sudo apt-get update
            cd hashbuzz-dev/dApp-backend
            git pull origin staging
            # Check if npm is in PATH and print node and npm versions
            echo "Node version: $(node -v)" 
            echo "NPM version: $(npm -v)"
            /usr/bin/npm install 
            /usr/bin/npm run db:push 
            /usr/bin/npm run build
